spring:
  h2:
    console:
      path: /h2-console
      enabled: true

  datasource:
    url: jdbc:h2:mem:payment;
    driver-class-name: org.h2.Driver
    username: leo
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect